#! /bin/sh

# fake the module hierarchy for uninstalled shared objects

libdir="`pwd`/.libs"
libexecdir="./.libexec"

libs="rep.io.db.gdbm rep.io.db.sdbm rep.i18n.gettext rep.io.readline \
      rep.lang.record-profile rep.data.tables rep.io.timers \
      rep.vm.safe-interpreter rep.io.sockets rep.util.md5"

rm -rf $libexecdir

for f in $libs; do
  g=`echo $f | tr . /`
  src=$libdir
  dest=$libexecdir/`dirname $g`
  for b in `( cd $libdir && echo *\`basename $g\`.* )`; do
    rm -f $dest/$b
    echo "$src/$b -> $dest/$b"
    ../mkinstalldirs $dest
    ln -s $src/$b $dest/$b
  done
done
